version: "2"
services:
  db:
    build:
      context: ./
      dockerfile: docker/dev/db.Dockerfile
    image: spa_db
    container_name: spa_db_1
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: docker
      MYSQL_DATABASE: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33060:3306"
    #volumes:
    # - ./docker/dev/db:/mysql/data

  web:
    build:
      context: ./
      dockerfile: docker/dev/web.Dockerfile
    image: spa_web
    container_name: spa_web_1
    ports:
      - "8089:80"
    volumes_from:
    - app

  node:
    build:
      context: ./
      dockerfile: docker/dev/node.Dockerfile
    image: spa_node
    container_name: spa_node_1
    tty: true
    volumes:
      - ./:/var/www

  app:
    build:
      context: ./
      dockerfile: docker/dev/app.Dockerfile
    image: spa_app
    container_name: spa_app_1
    volumes:
    - ./:/var/www
    #- ~/.ssh:/home/docker-user/.ssh -- pass your local ssh key
    depends_on:
      - db
