version: '3'

services:
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: spa_db_1
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33061:3306"
    networks:
      - spa-network

  web:
    build:
      context: ./
      dockerfile: docker/dev/web.Dockerfile
    image: spa_web
    container_name: spa_web_1
    ports:
      - "8089:80"
    volumes:
      - ./docker/dev/config/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - spa-network

  app:
    build:
      context: docker/dev
      dockerfile: app.Dockerfile
    image: spa_app
    container_name: spa_app_1
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - spa-network

#Docker Networks
networks:
  spa-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

#Volumes
volumes:
  dbdata:
    driver: local
